version: "3.1"

services: 
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start #o podemos usar "node index.js"
